using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using SplineMesh;
//using UnityEngine.ProBuilder.BezierShape;
public class makebezierspline : MonoBehaviour
{
    SplineNode node1, node2;
    Vector3 toAdd=new Vector3(0.01f,0.01f,0.01f);
    // Start is called before the first frame update
    void Start()
    {
        //this.gameObject.GetComponent<BezierShape>();
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown("k")){
            Debug.Log("sxaff");
            Vector3 node1vec=new Vector3(3,5.5f,-7);
            Vector3 node2vec=new Vector3(3.5f,6,-8f);
            

            node1= new SplineNode(node1vec,node1vec);
            node1.Position=node1.Position-toAdd;            
            node1.Direction=node1.Direction+toAdd;
            node2= new SplineNode(node2vec, node2vec);
            node2.Position=node2.Position-toAdd;            
            node2.Direction=node2.Direction+toAdd;
            //this.gameObject.GetComponent<Spline>().InsertNode(1,node1);
            //this.gameObject.GetComponent<Spline>().InsertNode(1,node2);
            this.gameObject.GetComponent<Spline>().nodes[0].Position=node1vec;
            //this.gameObject.GetComponent<Spline>().nodes[0].Direction=node1vec;
            this.gameObject.GetComponent<SplineMeshTiling>().enabled=true;

            Debug.Log("found"+this.gameObject.transform.Find("generated by SplineMeshTiling"));
            Object.Destroy(this.gameObject.transform.Find("generated by SplineMeshTiling").gameObject,1);
            //this.gameObject.GetComponent<SplineMeshTiling>().enabled=false;
            //node1.Position=node1.Position-toAdd;
            //node2.Position=node2.Position-toAdd;
        }
        if (Input.GetKeyDown("m")){
            node1.Position=node1.Position-toAdd;
        }
        if (Input.GetKeyDown("n")){
            node2.Position=node2.Position-toAdd;
        }
    }
}
